/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tideminer2014;

/**
 *
 * @author Chris
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField_e01 = new javax.swing.JTextField();
        jTextField_e02 = new javax.swing.JTextField();
        jTextField_e03 = new javax.swing.JTextField();
        jTextField_e04 = new javax.swing.JTextField();
        jTextField_e05 = new javax.swing.JTextField();
        jTextField_e06 = new javax.swing.JTextField();
        jTextField_e07 = new javax.swing.JTextField();
        jTextField_e08 = new javax.swing.JTextField();
        jTextField_e09 = new javax.swing.JTextField();
        jTextField_e10 = new javax.swing.JTextField();
        jTextField_e11 = new javax.swing.JTextField();
        jTextField_e12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_e01_flood_duration = new javax.swing.JLabel();
        jLabel_e01_flood_count = new javax.swing.JLabel();
        jLabel_e02_flood_count = new javax.swing.JLabel();
        jLabel_e02_flood_duration = new javax.swing.JLabel();
        jLabel_e03_flood_count = new javax.swing.JLabel();
        jLabel_e03_flood_duration = new javax.swing.JLabel();
        jLabel_e04_flood_count = new javax.swing.JLabel();
        jLabel_e04_flood_duration = new javax.swing.JLabel();
        jLabel_e05_flood_count = new javax.swing.JLabel();
        jLabel_e05_flood_duration = new javax.swing.JLabel();
        jLabel_e06_flood_count = new javax.swing.JLabel();
        jLabel_e06_flood_duration = new javax.swing.JLabel();
        jLabel_e07_flood_count = new javax.swing.JLabel();
        jLabel_e07_flood_duration = new javax.swing.JLabel();
        jLabel_e08_flood_count = new javax.swing.JLabel();
        jLabel_e08_flood_duration = new javax.swing.JLabel();
        jLabel_e09_flood_count = new javax.swing.JLabel();
        jLabel_e09_flood_duration = new javax.swing.JLabel();
        jLabel_e10_flood_count = new javax.swing.JLabel();
        jLabel_e10_flood_duration = new javax.swing.JLabel();
        jLabel_e11_flood_count = new javax.swing.JLabel();
        jLabel_e11_flood_duration = new javax.swing.JLabel();
        jLabel_e12_flood_count = new javax.swing.JLabel();
        jLabel_e12_flood_duration = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2. Enter Elevations");

        jTextField_e01.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e02.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e03.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e04.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e05.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e06.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e07.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e08.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e09.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e10.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e11.setPreferredSize(new java.awt.Dimension(120, 20));

        jTextField_e12.setPreferredSize(new java.awt.Dimension(120, 20));

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("3. Analyze");

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setText("1. Load Tide Data");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("4. Inspect Results");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("# floods");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("time flooded");

        jLabel_e01_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e01_flood_duration.setText("time flooded");

        jLabel_e01_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e01_flood_count.setText("# floods");

        jLabel_e02_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e02_flood_count.setText("# floods");

        jLabel_e02_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e02_flood_duration.setText("time flooded");

        jLabel_e03_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e03_flood_count.setText("# floods");

        jLabel_e03_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e03_flood_duration.setText("time flooded");

        jLabel_e04_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e04_flood_count.setText("# floods");

        jLabel_e04_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e04_flood_duration.setText("time flooded");

        jLabel_e05_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e05_flood_count.setText("# floods");

        jLabel_e05_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e05_flood_duration.setText("time flooded");

        jLabel_e06_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e06_flood_count.setText("# floods");

        jLabel_e06_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e06_flood_duration.setText("time flooded");

        jLabel_e07_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e07_flood_count.setText("# floods");

        jLabel_e07_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e07_flood_duration.setText("time flooded");

        jLabel_e08_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e08_flood_count.setText("# floods");

        jLabel_e08_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e08_flood_duration.setText("time flooded");

        jLabel_e09_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e09_flood_count.setText("# floods");

        jLabel_e09_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e09_flood_duration.setText("time flooded");

        jLabel_e10_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e10_flood_count.setText("# floods");

        jLabel_e10_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e10_flood_duration.setText("time flooded");

        jLabel_e11_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e11_flood_count.setText("# floods");

        jLabel_e11_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e11_flood_duration.setText("time flooded");

        jLabel_e12_flood_count.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e12_flood_count.setText("# floods");

        jLabel_e12_flood_duration.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_e12_flood_duration.setText("time flooded");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setText("5. Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("or 5. Copy (& Paste)");

        jMenu1.setText("File");

        jMenuItem2.setText("Load Tide Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save Analysis");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Info");

        jMenuItem4.setText("About");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setText("Help");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_e02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_e12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e02_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e02_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e01_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e01_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e03_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e03_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e04_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e04_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e05_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e05_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e06_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e06_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e07_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e07_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e08_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e08_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e09_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e09_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e10_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e10_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e11_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e11_flood_duration))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_e12_flood_count)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel_e12_flood_duration)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e01_flood_count)
                            .addComponent(jLabel_e01_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e02_flood_count)
                            .addComponent(jLabel_e02_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e03_flood_count)
                            .addComponent(jLabel_e03_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e04_flood_count)
                            .addComponent(jLabel_e04_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e05_flood_count)
                            .addComponent(jLabel_e05_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e06_flood_count)
                            .addComponent(jLabel_e06_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e07_flood_count)
                            .addComponent(jLabel_e07_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e08_flood_count)
                            .addComponent(jLabel_e08_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e09_flood_count)
                            .addComponent(jLabel_e09_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e10_flood_count)
                            .addComponent(jLabel_e10_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e11_flood_count)
                            .addComponent(jLabel_e11_flood_duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_e12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_e12_flood_count)
                            .addComponent(jLabel_e12_flood_duration)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_e01_flood_count;
    private javax.swing.JLabel jLabel_e01_flood_duration;
    private javax.swing.JLabel jLabel_e02_flood_count;
    private javax.swing.JLabel jLabel_e02_flood_duration;
    private javax.swing.JLabel jLabel_e03_flood_count;
    private javax.swing.JLabel jLabel_e03_flood_duration;
    private javax.swing.JLabel jLabel_e04_flood_count;
    private javax.swing.JLabel jLabel_e04_flood_duration;
    private javax.swing.JLabel jLabel_e05_flood_count;
    private javax.swing.JLabel jLabel_e05_flood_duration;
    private javax.swing.JLabel jLabel_e06_flood_count;
    private javax.swing.JLabel jLabel_e06_flood_duration;
    private javax.swing.JLabel jLabel_e07_flood_count;
    private javax.swing.JLabel jLabel_e07_flood_duration;
    private javax.swing.JLabel jLabel_e08_flood_count;
    private javax.swing.JLabel jLabel_e08_flood_duration;
    private javax.swing.JLabel jLabel_e09_flood_count;
    private javax.swing.JLabel jLabel_e09_flood_duration;
    private javax.swing.JLabel jLabel_e10_flood_count;
    private javax.swing.JLabel jLabel_e10_flood_duration;
    private javax.swing.JLabel jLabel_e11_flood_count;
    private javax.swing.JLabel jLabel_e11_flood_duration;
    private javax.swing.JLabel jLabel_e12_flood_count;
    private javax.swing.JLabel jLabel_e12_flood_duration;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_e01;
    private javax.swing.JTextField jTextField_e02;
    private javax.swing.JTextField jTextField_e03;
    private javax.swing.JTextField jTextField_e04;
    private javax.swing.JTextField jTextField_e05;
    private javax.swing.JTextField jTextField_e06;
    private javax.swing.JTextField jTextField_e07;
    private javax.swing.JTextField jTextField_e08;
    private javax.swing.JTextField jTextField_e09;
    private javax.swing.JTextField jTextField_e10;
    private javax.swing.JTextField jTextField_e11;
    private javax.swing.JTextField jTextField_e12;
    // End of variables declaration//GEN-END:variables
}
